
language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - tools
    - platform-tools
    - android-28
    - build-tools-28.0.3
    - -extra

  notifications:
    email: false

before_install:
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew clean build
  - ./gradlew test
